myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views

from .views import *

urlpatterns = [
    url(r'^$', views.login),
    url(r'^create_root/$', create_root),
    url(r'^create_node/$', create_node),
    url(r'^insrow/$', insrow),
    url(r'^show_trees/$', show_trees),
    url(r'^show_node/$', show_node),
    url(r'^save_node/$', save_node),
    url(r'^tree_details/$', tree_details),
    url(r'^delete_node/$', delete_node),
    url(r'^save_table/$', save_table),
    url(r'^logout/$', logout_page),
]

progettoDjango/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/',include("myapp.urls")),
    url(r'^accounts/login/',include("myapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from __future__ import unicode_literals

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.core.urlresolvers import reverse
import datetime

class Node(MPTTModel):

    TUMOR = (
        ('S', 'Solid'),
        ('A', 'Ascites'),
    )
    SITE = (
        ('S', 'Subcute'),
        ('I', 'IpSlice'),
        ('C', 'IpCells'),
    )
    POSITION = (
        ('L', 'Left'),
        ('R', 'Right'),
    )
    TREATMENT = (
        ('N', 'No'),
        ('S', 'StartingDate'),
        ('T', 'Type'),
        ('D', 'Dose'),
        ('A', 'AdministratorRoute'),
    )
    
    name = models.CharField(default='0000000',max_length=20,unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    date = models.DateField(null=True,blank=True)
    tumor = models.CharField(max_length=1, choices=TUMOR,null=True,blank=True)
    anatomic_pathology = models.CharField(max_length=60,null=True,blank=True)
    tumor_markers = models.CharField(max_length=60,null=True,blank=True)
    site = models.CharField(max_length=1, choices=SITE,null=True,blank=True)
    position = models.CharField(max_length=1, choices=POSITION,null=True,blank=True)
    treatment = models.CharField(max_length=1, choices=TREATMENT,null=True,blank=True)
    
    age = models.IntegerField(null=True,blank=True)
    actual_state = models.CharField(max_length=60,null=True,blank=True)

    def __unicode__(self):
        return self.name

class TimeVolume(models.Model):

    time = models.IntegerField()
    volume = models.IntegerField()
    datins = models.DateTimeField(auto_now_add=True)

    node = models.ForeignKey(Node, on_delete=models.CASCADE) #1 a n

    def __unicode__(self):
        return str(self.node)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Stage</title>
        <link rel="stylesheet" href="{% static 'css/reset.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/main.css' %}"/>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
	<!--  start header  -->
	<header>
	    <div class="wrapper">
		<div id="us" class="logo">
		    User: {{request.user}}
		</div>
		<nav>
		    <ul>
		        <li><a href="/myapp/show_trees"> Show Trees</a> </li>
		        <li><a href="/myapp/create_root"> Create Root</a></li> 
		        <!--<li><a href="/myapp/create_table"> Create Table</a>  </li>-->
			<li><a href="/myapp/logout"> Logout</a>  </li>
		    </ul>
		</nav>
	    </div>
	</header><!--  end header  -->
    {% block content %}{% endblock content %}
	<!--  start footer  -->
	<footer>
	    <div class="wrapper">
		<section class="copyrights">
		    <p>Devoloped by Jacopo Gardini</p>
		</section>
		<!--  footer navigation  -->			
	    </div>
	</footer><!--  end footer  -->  
    </body>
</html>

templates/baselog.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Stage</title>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/logincss.css' %}">
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

templates/create_root.html
{% extends "base.html" %}
{% block content %}
<!--  start menu  -->
	<section class="menu">
            <div class="wrapper">
                <div class="menu_title">
                        <h2>Create Root</h2>
                </div>
                <div class="mean_menu">
                    <!--  left menu row  -->
                    <article >
			<form action="" class="form2" method="post">{% csrf_token %}
				<table class="table1">{{ form.as_table }}<tr><td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<br></td></tr><tr><td></td><td><input type="submit" name="submit" value="Create Root"/></td></tr></table>
			</form>
                        
                    </article>             
                </div>                               
            </div>           
        </section><!--  end menu  -->

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
<!--  start hero  -->
<section class="hero">
    <div class="caption">
        <h3></h3>		
    </div>
</section><!--  end hero  -->  
<!--  start footer  -->
{% endblock %}

templates/show_trees.html
{% extends "base.html" %}
{% block content %}
<!--  start menu  -->
	<section class="menu">
            <div class="wrapper">
                <div class="menu_title">
                        <h2>Show Trees</h2>
                </div>
                <div class="mean_menu">
                    <!--  left menu row  -->
                    <article >
			<form class="form2" action="/myapp/tree_details/" method="post">{% csrf_token %}
				<table class="table1">
					<tr><td class="td1"><input type="submit" name="submit" class="inp" value="Go to tree"></td><td><select class="styled-select slate" id="sel" name="opt">
						{% for obj in treeslist %}
	  						<option value="{{obj.name}}">{{obj.name}}</option>
						{% endfor %}
					</select></td></tr>
				</table>
			</form> 
                    </article>             
                </div>                               
            </div>           
        </section><!--  end menu  -->
{% endblock %}

templates/tree_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
<!--<script src="http://d3js.org/d3.v3.min.js" type="text/javascript"></script>-->
<script src="{% static 'js/d3/d3.js' %}" type="text/javascript"></script> 
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script> 
<script src="{% static 'js/javas.js' %}" type="text/javascript"></script>
<div id="trcont"></div>

<script type="text/javascript">
	//console.log(JSON.stringify([{{jsonlist|safe}}]));
	var jst = JSON.stringify([{{jsonlist|safe}}]);
	my(jst);
</script>

<div class="myDiv">
<input type="hidden" id="nodd3" name="nodd3" value=""/>
<table class="myTab">
<tr>
<td>
<form class="hide" id="ftab2" method="POST" action="../create_node/">{% csrf_token %}
  <fieldset>
  <legend>Create Node:</legend>
  <input type="hidden" name="opt" value="{{ root.id }}"/>
  <table id="crtab2" class="table1"></table>
  </fieldset>
</form>
</td>
<td><br>
</td>
</tr>
<tr>
<td>
<form class="hide" id="frmnod" method="POST" action="../save_node/" >{% csrf_token %}
<fieldset>
  <legend>Node Information:</legend>
  <input type="hidden" name="opt" value="{{ root.id}}"/>
  <table id="tbnode" class="table1"></table>
  </fieldset>
</form>
</td>
<td>
<form class="hide" id="frmrow" method="POST" action="../save_table/">{% csrf_token %}
  <fieldset>
  <legend>Times/Volumes Information:</legend>
  <input type="hidden" name="opt" value="{{ root.id }}"/>
  <table id="table" class="table1"></table>
  </fieldset>
</form>
<form class="hide" id="ftab" method="POST" action="../insrow/">{% csrf_token %}
<fieldset>
  <legend>Insert Time/Volume:</legend>
  <input type="hidden" name="opt" value="{{ root.id }}"/>
  <table id="crtab" class="table1"></table>
</fieldset>
</form>
</td>
</tr>
<tr>
<td>
<form class="hide" id="frmdel" method="POST" action="../delete_node/" >{% csrf_token %}
<fieldset>
  <legend>Delete Node:</legend>
  <input type="hidden" name="opt" value="{{ root.id }}"/>
  <input type="hidden" id="idhid" name="hiddel" />
  <table id="tbdel" class="table1"></table>
</fielset>
</form>
</td>
<td>

</td>
</tr>
</table>
</div>
<script >
 $(document).ready(function(){
	$(".hide").hide(); 
	$(".myDiv").hide();
});
</script>

<script type="text/javascript">
    var frm = $('#frmnod');
    frm.submit(function (ev) {
	var inp = document.getElementById("frmnod").elements;
	var ok = true;
	for(i=0;i<inp.length;i++){
		if(inp[i].value == ""){
			ok=false
		}
	}
	if(ok){
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: $("#frmnod :input").serialize(),
            success: function (json) {
		$("#trcont").empty();
		$('#ftab2').empty();
		var jlist=JSON.stringify([JSON.parse(json.datajs)]);
		my(jlist);
            }
        });
	}else{alert("Please fill all fields");}
        ev.preventDefault();
    });

    var frm2 = $('#frmdel');
    frm2.submit(function (ev) {
        $.ajax({
            type: frm2.attr('method'),
            url: frm2.attr('action'),
            data: $("#frmdel :input").serialize(),
            success: function (json) {
		$("#trcont").empty();
		$("#tbnode").empty();
		$("#tbdel").empty();
		$("#table").empty();
		$('#crtab').empty();
		if(json.datajs==="radice"){
			$('#trcont').append('Albero eliminato');
		}else{
			var jlist2=JSON.stringify([JSON.parse(json.datajs)]);
			my(jlist2);
		}
                $(".myDiv").hide();
            }
        });
        ev.preventDefault();
    });

    var frmrig = $("#frmrow");
	frmrig.submit(function (ev) {
	var inp = document.getElementById("frmrow").elements;
	var ok = true;
	for(i=0;i<inp.length;i++){
		if(inp[i].value == ""){
			ok=false
		}
	}
	if(ok){
		$.ajax({
		    type: frmrig.attr('method'),
		    url: frmrig.attr('action'),
		    data: frmrig.serialize(),
		    success: function (json) {
			$("#trcont").empty();
			//$("#table").empty();
			if(json.dele){
				for(i=0;i<json.dele.length;i++){
					$("#row"+json.dele[i]).remove();
					console.log(json.dele[i]);
				}
			}
			if ($('#table tr').length == 2) {
				console.log("passssss");
				if($("#idUp")){
			    		$("#idUp").remove();
				}
			}
			var jlist3=JSON.stringify([JSON.parse(json.datajs)]);
			my(jlist3);
		    }
		});
		}else{alert("Please fill all fields");}
		ev.preventDefault();
	    });
    
    var ftab = $('#ftab');
    ftab.submit(function (ev) {
	var inp = document.getElementById("ftab").elements;
	var ok = true;
	for(i=0;i<inp.length;i++){
		if(inp[i].value == ""){
			ok=false
		}
	}
	if(ok){
        $.ajax({
            type: ftab.attr('method'),
            url: ftab.attr('action'),
            data: ftab.serialize(),
            success: function (json) {
		$("#trcont").empty();
		var jlist5=JSON.stringify([JSON.parse(json.datajs)]);
		my(jlist5);
		$("#table").empty();
		var table=$("#table");
		if(json.table[0]){
			table.append('<tr><td><input type="hidden" name="node" value= "'+json.table[0].node+'"></td></tr>');			
			for(i=0;i<json.table.length;i++){
				//console.log(i);
				table.append('<tr id="row'+json.table[i].id+'"><td><input type="text" name="time" value= "'+json.table[i].time+'"></td><td><input type="text" name="volume" value="'+json.table[i].volume+'"></td><td><input type="checkbox" name="delete" value="'+json.table[i].id+'"></td><td><input type="hidden" name="id" value="'+json.table[i].id+'"></td></tr>');
			}
			table.append('<tr><td><input type="submit" id="idUp" name="submit" value="Update"></td></tr>');
			$("#id_time").val('');
			$("#id_volume").val('');
		}
            }
        });
	}else{alert("Please fill all fields");}
        ev.preventDefault();
    });

	var cre = $('#ftab2');
	    cre.submit(function (ev) {
		var inp = document.getElementById("ftab2").elements;
		var ok = true;
		for(i=0;i<inp.length;i++){
			if(inp[i].value == ""){
				ok=false
			}
		}
		if(ok){
		$.ajax({
		    type: cre.attr('method'),
		    url: cre.attr('action'),
		    data: cre.serialize(),
		    success: function (json) {
			$("#trcont").empty();
			var jli=JSON.stringify([JSON.parse(json.datajs)]);
			my(jli);
			$("#table").empty();
		    }
		});
		}else{alert("Please fill all fields");}
		ev.preventDefault();
	    });
    
    
</script>

{% endblock %}